### ISSUE TITLE
Not really an issue :P

### ISSUE THREAD

**Issue by iscle** [davidwim/GPS365#1]
Well, I've just started writing an alternative app for Android for 365GPS (GPS365) trackers and found this repository (the only one other than mine: https://github.com/Iscle/My-GPS-Tracker)

I have reverse-engineered the entire API from the Android app, so if you have any questions we can talk privately.

I'm planning to finish the basic functionality of that app in around 1 week maximum and publish it on the Play Store. That said, I still don't own any trackers, they are on their way. If you want to collaborate, I could test some API endpoints with your devices if you want to.

Anyway, I just wanted to contact you and this was the only way haha

**Comment by W1MMER** [comment]
I've sent you an email.

**Comment by iscle** [comment]
Awesome!
