### ISSUE TITLE
Other commands

### ISSUE THREAD

**Issue by pergolafabio** [davidwim/GPS365#2]
Hey,

how did you obtain those commands? nice job!

do you also have more? like remote turn on , or set the schedule interval ?

thnx in advance

**Comment by W1MMER** [comment]
Hi, I just used a mitm proxy on the main app.

Unfortuantly I do not have anymore commands, well I might, but I have completely gone off this project.

<img width="285" alt="Screen Shot 2021-12-14 at 8 29 00 PM" src="https://user-images.githubusercontent.com/63693881/145952484-4958dac9-563c-416a-a763-828c522b95ff.png">

**Comment by pergolafabio** [comment]
Hi, nevermind, also used a proxy, so I have the ones i need
