### ISSUE TITLE
New api

### ISSUE THREAD

**Issue by pergolafabio** [davidwim/GPS365#3]
Hey @W1MMER  seems there is a change in the url, some kind of AK token... Did you get it to work?

http://47.75.106.117/api_ilist.php?imei=....

**Comment by J-o-h-n-M** [comment]
Same issue, ak seems some kind of time string. I have also reached out by email to topin sales to ask them if there is an alternative call that we can do. But not sure if/how they will respond. Found their email in this post: https://gist.github.com/emilio-martinez/11019f04c5b05e3f7f753eaca0e58941

**Comment by W1MMER** [comment]
I'm not quite sure either. I don't have the trackers anymore but I've still got the app so I'll do some testing tomorrow.

I did notice with the GPS365 app, one of the routes it was hitting (http://www.365gps.net/api_route.php?imei=359339075455302) returned:

```
{
  "result": "Errcode:404"
}
````

**Comment by pergolafabio** [comment]
An alternative road is using the webportal, haven't investigated yet

**Comment by J-o-h-n-M** [comment]
I managed to create a python script that does seem to create a valid url. See here: https://community.home-assistant.io/t/using-the-results-of-a-simple-gps-rest-call/362510/74
